### ISSUE TITLE
storage-config secret format is different between kserve and modelmesh

### ISSUE THREAD

**Issue by Jooho** [opendatahub-io/odh-model-controller#115]
odh-model-controller is responsible for generating `storage-config` which is the main secret to accessing models.

For modelmesh, the secret `storage-config` is 
~~~
{"access_key_id":"AKIAIOSFODNN7EXAMPLE","default_bucket":"modelmesh-example-models","endpoint_url":"http://minio:9000","region":"us-south","secret_access_key":"wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY","type":"s3"}
~~~

but for kserve, it looks like
~~~
apiVersion: v1
data:
  AWS_ACCESS_KEY_ID: YWRtaW4=
  AWS_SECRET_ACCESS_KEY: cGFzc3dvcmQ=
kind: Secret
metadata:
  annotations:
    serving.kserve.io/s3-endpoint: minio.minio.svc:9000
    serving.kserve.io/s3-region: us-east-2
    serving.kserve.io/s3-useanoncredential: "false"
    serving.kserve.io/s3-usehttps: "0"
  name: storage-config
~~~

odh-model-controller needs to generate right format of storage-config secret based on deployment type(kserve, modelmesh)

**Comment by spolti** [comment]
feel free to assign to me, can handle after the CVE stuff

**Comment by Jooho** [comment]
@spolti thank! when @VedantMahabaleshwarkar sends a PR, please review it.

**Comment by VedantMahabaleshwarkar** [comment]
Overall the storage secret can remain the same, the only difference is the name of the `key` for the bucket. Kserve expects the key `bucket` while Modelmesh expects the key `default_bucket`. I've added both as a patch so that it works. However we should open an issue upstream to have the same format everywhere

**Comment by heyselbi** [comment]
@VedantMahabaleshwarkar please attach the RHODS PRs once they are open/merged.
