### ISSUE TITLE
Fails when running on IBM OpenShift cluster

### ISSUE THREAD

**Issue by eyalcha** [opendatahub-io/odh-model-controller#170]
I have installed ODH 2.8.0 with only KFP & KServe enabled (Managed). I get the following error from `odh-model-controller`

Edgar Hernandez @israel-hdez 

[odh-model-controller-96f84f484-wz475-manager.log](https://github.com/opendatahub-io/odh-model-controller/files/14393638/odh-model-controller-96f84f484-wz475-manager.log)

**Comment by israel-hdez** [comment]
Hi, @eyalcha.
We have a new dependency on Authorino. At the moment, there is no way to opt-out.

You can read more in this draft I have written: https://github.com/opendatahub-io/kserve/pull/253/files?short_path=30fb6fd#diff-30fb6fd57359405eaaa89c465c59b75c6f7230d3140d7c0e9d6857b48b6c06ec

**Comment by israel-hdez** [comment]
I think we already solved this offline.
I'll close this ticket.
