### ISSUE TITLE
Review KCS Draft SOPs for ModelMesh Serving

### ISSUE THREAD

**Issue by maryfrances01** [opendatahub-io/odh-model-controller#72]
We are in the process of migrating the RHODS Standard Operating Procedures (SOPs) from our internal GitLab repository to the KCS solutions platform. This migration aims to consolidate all SOPs into one accessible location, promoting collaboration across teams including engineering, SRE, and CEE.

This consolidation ensures that anyone working with a customer, and potentially the customers themselves once solutions mature, will have access to this centralized knowledge repository.

As part of this effort, draft KCS SOPs have been created for the existing SOPs. I kindly request the expertise of an engineer to review the draft KCS SOPs and provide feedback on the following two items:

1. **Accuracy of Commands:** Some SOPs in GitLab lacked precise steps, which have been added to the KCS drafts based on my testing. Please verify the accuracy of commands in the KCS drafts and let me know if any of the steps should be changed/improved.

1. **Context, Symptoms, and Impact of Alerts Firing:** Provide additional context, symptoms, and impact insights for alerts. If possible, identify dependencies on other components and suggest pre-escalation checks for SRE and CEE teams. Are there any additional checks that SRE or CEE could perform before requesting engineering support, which are not currently outlined in the SOPs?

The KCS drafts for ModelMesh Serving can be reviewed here:

[7025310](https://access.redhat.com/solutions/7025310)
[7025312](https://access.redhat.com/solutions/7025312)

Feel free to reach out to me with any questions.

**Comment by Jooho** [comment]
I think the KCSs you created are the good starting point to gather logs for modelmesh/odh-model-controller and also logs for other components. I think it is a good idea to make it as landing trouble shooting KCS for RHODS. Then add sub link like modelmesh or kserve KCSs .. odh-model-controller log are always needed for both cases

**Comment by heyselbi** [comment]
@maryfrances01 are there any outstanding drafts we need to look into?

**Comment by maryfrances01** [comment]
@heyselbi No, the draft has been updated and I will publish it once the other component drafts are complete. Thanks - I'll close this!
