### ISSUE TITLE
Parametrize hardcoded env var in odh-model-controller

### ISSUE THREAD

**Issue by vaibhavjainwiz** [opendatahub-io/odh-model-controller#85]
Currently multple Env var are hard coded to expedite implementation. These Env par should be properly parametrize to receive their there value from outside. 
example :
```
IstioNamespace      = "istio-system"
IstioIngressService = "istio-ingressgateway"
```

**Comment by vaibhavjainwiz** [comment]
Make labels of NetworkPolicy configurable.
https://github.com/opendatahub-io/odh-model-controller/blob/5832dbf2469408f465664d38bbb8dfc0d0310786/controllers/reconcilers/kserve_networkpolicy_reconciler.go#L64C5-L64C63

**Comment by israel-hdez** [comment]
Migrated to: https://issues.redhat.com/browse/RHOAIENG-1044
